### ISSUE TITLE
When enter , . on russian keybord - is activated search mode

### ISSUE THREAD

**Issue by bigperson** [ek0519/nova-quilljs#1]
When i enter , .  (/?) on Russian keybord - is activated search mode

**Comment by ek0519** [comment]
@bigperson Can you give more information , like image  etc
![Screen Shot 2019-12-19 at 12 05 37 PM](https://user-images.githubusercontent.com/14010093/71144121-dfc5c200-2257-11ea-9267-404010858b49.png)

you mean **search mode** like this 

https://nova.laravel.com/docs/2.0/search/global-search.html#title-subtitle-attributes

<img width="462" alt="global-search 0f03a2d1" src="https://user-images.githubusercontent.com/14010093/71144231-4ba82a80-2258-11ea-9f10-bbe7b91dbf14.png">

trigger keyboard shortcuts?
https://nova.laravel.com/docs/2.0/resources/#keyboard-shortcuts

**Comment by bigperson** [comment]
@ek0519 I can not print the dot. The search mode is activated.

https://youtu.be/iPuxuWRCRxc

**Comment by ek0519** [comment]
> @ek0519 I can not print the dot. The search mode is activated.
> 
> https://youtu.be/iPuxuWRCRxc

thanks for your video, let me know this bug....I need some time

**Comment by ek0519** [comment]
@bigperson This bug might not be resolve. [ref nova issue](https://github.com/laravel/nova-issues/issues/1370), sorry

**Comment by angauber** [comment]
Not sure if this is the same bug but I add the issue with a similar package:
https://github.com/numaxlab/nova-ckeditor5-classic/pull/10

Adding the `form-control` css class to the div should do the trick.

Cheers,
Antoine
