### ISSUE TITLE
Error when updating Nova from v3.8.4 to v3.9.2

### ISSUE THREAD

**Issue by mennotempelaar** [ek0519/nova-quilljs#11]
Hey there,

First of all, I like your package very much!

The placeholder method which is being used within the `Ek0519\Quilljs\Quilljs` class overrides the placeholder method within the `Laravel\Nova\Fields\Field`.

I guess within these updates the placeholder method has been changed to:

```php
/**
 * Set the placeholder text for the field if supported.
 *
 * @param string $text
 * @return $this
 */
public function placeholder($text)
{
    $this->placeholder = $text;
    $this->withMeta(['extraAttributes' => ['placeholder' => $text]]);

    return $this;
}
```

This gives an error like this:

```
Declaration of Ek0519\Quilljs\Quilljs::placeholder(string $value) should be compatible with Laravel\Nova\Fields\Field::placeholder($text) {"userId":1,"exception":"[object] (ErrorException(code: 0): Declaration of Ek0519\\Quilljs\\Quilljs::placeholder(string $value) should be compatible with Laravel\\Nova\\Fields\\Field::placeholder($text) at /vendor/ek0519/quilljs/src/Quilljs.php:53)
```

So I did change the placeholder method within the `Ek0519\Quilljs\Quilljs` class to:

```php
public function placeholder($text)
{
    return $this->withMeta(['placeholder'=> $text]);
}
```

And this fixes the issue.

I don't know how you want to update this; Should I send you a PR?

**Comment by ek0519** [comment]
> Hey there,
> 
> First of all, I like your package very much!
> 
> The placeholder method which is being used within the `Ek0519\Quilljs\Quilljs` class overrides the placeholder method within the `Laravel\Nova\Fields\Field`.
> 
> I guess within these updates the placeholder method has been changed to:
> 
> ```
> /**
>  * Set the placeholder text for the field if supported.
>  *
>  * @param string $text
>  * @return $this
>  */
> public function placeholder($text)
> {
>     $this->placeholder = $text;
>     $this->withMeta(['extraAttributes' => ['placeholder' => $text]]);
> 
>     return $this;
> }
> ```
> 
> This gives an error like this:
> 
> ```
> Declaration of Ek0519\Quilljs\Quilljs::placeholder(string $value) should be compatible with Laravel\Nova\Fields\Field::placeholder($text) {"userId":1,"exception":"[object] (ErrorException(code: 0): Declaration of Ek0519\\Quilljs\\Quilljs::placeholder(string $value) should be compatible with Laravel\\Nova\\Fields\\Field::placeholder($text) at /vendor/ek0519/quilljs/src/Quilljs.php:53)
> ```
> 
> So I did change the placeholder method within the `Ek0519\Quilljs\Quilljs` class to:
> 
> ```
> public function placeholder($text)
> {
>     return $this->withMeta(['placeholder'=> $text]);
> }
> ```
> 
> And this fixes the issue.
> 
> I don't know how you want to update this; Should I send you a PR?

sure! thank bro, I try in nova 2.12.0 and 3.10 , your code was perfect!
