### ISSUE TITLE
Editor overlaps field below.

### ISSUE THREAD

**Issue by piotrh052b** [ek0519/nova-quilljs#14]
The editor overlaps any fields below in Chrome or Firefox

![Zrzut ekranu 2020-11-21 170147](https://user-images.githubusercontent.com/64467371/99881680-68dd3a00-2c1b-11eb-88d3-538792c59fe3.png)

**Comment by ek0519** [comment]
@piotrh052b 
I release new version 0.3.1, add **->paddingBottom(integer)** , you can modify it.
