### ISSUE TITLE
404 error on image upload

### ISSUE THREAD

**Issue by piotrh052b** [ek0519/nova-quilljs#15]
![Zrzut ekranu 2020-11-21 170811](https://user-images.githubusercontent.com/64467371/99881796-2cf6a480-2c1c-11eb-9822-32c3772badaa.png)

 I have done all the steps:
 composer require ek0519/quilljs
 php artisan vendor:publish --provider="Ek0519\Quilljs\FieldServiceProvider"
 php artisan migrate
 php artisan storage:link

Laravel Nova ver 3.14

**Comment by ek0519** [comment]
@piotrh052b 
![Screen Shot 2020-11-22 at 12 24 32 AM](https://user-images.githubusercontent.com/14010093/99882140-44a04e00-2c59-11eb-971d-eb2e6d7f4a34.png)

I guess you need to add  **->withFiles** set your storage.
![Screen Shot 2020-11-22 at 12 27 14 AM](https://user-images.githubusercontent.com/14010093/99882208-c7290d80-2c59-11eb-8729-9b799ceb0b48.png)

 v3.13.0
