### ISSUE TITLE
The image attachment does not getting save

### ISSUE THREAD

**Issue by duongtdvn** [ek0519/nova-quilljs#16]
Hi, firstly thank you for creating this awesome package! And I am implementing the field with image upload feature, the image uploaded and displayed fine. However, it does not move the record from `nova_pending_trix_attachments` table to `nova_trix_attachments` after resource updated. I am using the latest laravel nova version 3.18.0 with the original trix attachment do this fine. Could you please take a look?

**Comment by ek0519** [comment]
[ref](https://nova.laravel.com/docs/1.0/resources/fields.html#file-uploads) 

Finally, in your app/Console/Kernel.php file, you should register a daily job to prune any stale attachments from the pending attachments table and storage. Laravel Nova provides the job implementation needed to accomplish this:

```
use Laravel\Nova\Trix\PruneStaleAttachments;

$schedule->call(function () {
    (new PruneStaleAttachments)();
})->daily();
```

**Comment by duongtdvn** [comment]
But this is used for purge unused attachments, and does not mean to store them from pending isn't it?

**Comment by ek0519** [comment]
@duongtdvn 
I'm sorry to keep you waiting ><, you are right!

I study source code,
you can see the model `PendingAttachment` (in Laravel\Nova\Trix folder) has the method `persist`.

```php=
public function persist(Trix $field, $model)
    {
        $disk = $field->getStorageDisk();

        Attachment::create([
            'attachable_type' => get_class($model),
            'attachable_id' => $model->getKey(),
            'attachment' => $this->attachment,
            'disk' => $disk,
            'url' => Storage::disk($disk)->url($this->attachment),
        ]);

        $this->delete();
    
```
I already update 0.3.2 version, you can try it , but not 100% perfect, maybe you can help me.
