### ISSUE TITLE
请修改你的README文档内容

### ISSUE THREAD

**Issue by niming175** [ek0519/nova-quilljs#19]
你一个老外，请不要在readme里放入不利中国的内容链接，香港事务，你无权干预和评论，请删掉这些链接！像你这样不尊重国家主权的开发者， 代码也是不值得信任的。耗子尾汁！

You are a foreigner, please do not put in the readme adverse links to China, Hong Kong affairs, you have no right to intervene and comment, please delete these links! For developers like you who don't respect national sovereignty, code can't be trusted. Rat tail juice!

**Comment by ek0519** [comment]
I live in democratic country, Everyone has the right to freedom of expression, I stand with Hong Kong, Xinjiang, Uighur, Taiwan!

Get back GFW, Write your code, stop being foolish and grow wise.

**Comment by niming175** [comment]
> I live in democratic country, Everyone has the right to freedom of expression, I stand with Hong Kong, Xinjiang, Uighur, Taiwan!
> 
> Get back GFW, Write your code, stop being foolish and grow wise.

我知道你是崇尚民主自由，但你就一老外，你无权随便诋毁和干涉一个国家的主权，这又不是你的国家，你根本就不了解我国的民族和文化；全世界经常发生战乱，就是你这样多管闲事的人太多了。你一个码农，瞎管什么政治。
If you don't understand, try to translate by yourself

**Comment by ek0519** [comment]
I do not know what you say, but I fell you are so funny and childish.

GitHub was a company of American, guarantee freedom of speech for the people, if you do not like, fine, use your China network and the other git repository, happy coding and happy talking political topics, haha Taiwan No.1

**Comment by ek0519** [comment]
![image](https://user-images.githubusercontent.com/14010093/111480896-69bb4e00-876d-11eb-9612-01889da0dc73.jpeg)
