### ISSUE TITLE
Image alignments are causing problems - sometimes do not save, or sometimes get left aligned when reopening the editor for editing post

### ISSUE THREAD

**Issue by MHassanSaqib** [ek0519/nova-quilljs#20]
Hi there, 

This plugin is awesome. Just causing a problem for images - sometimes attached images do not save the alignment and sometimes they are aligned left automatically. The same kind of issue is also addressed in the following link. Could you assist me with how to resolve it? 

https://github.com/kensnyder/quill-image-resize-module/issues/10

Thanks

**Comment by reppair** [comment]
I also can not center or right-align the image.. any way to get this working for this package?

**Comment by ek0519** [comment]
This version  has two methods can align image. Next version I will close align active on image, because quilljs's toolbar already has align function, it maybe easily to use, thanks you ,guys.

**Comment by reppair** [comment]
I did not understand your answer @ek0519. Can you explain in a bit more detail please.
