### ISSUE TITLE
Editor Height

### ISSUE THREAD

**Issue by Milkhan** [ek0519/nova-quilljs#4]
Thank you for this great package. Is there any option to set a height for the editor? And is it possible to resize it?

**Comment by Milkhan** [comment]
I could find a way to set the height:

1- In NovaServiceProvider add a custom css file.

` 


    public function boot()
    {

        parent::boot();

        Nova::style('admin', public_path('css/custom.css')); // Set a custom css file.

    }
    
`

2. In the custom.css file (public/css/custom.css)

` 
   height:200px !important;

    margin-bottom: 50px;


`

I couldn't find a way to make it resizable. This didnt work:

` .ql-container {

    resize: both;

  overflow: auto;

  }
`

**Comment by ek0519** [comment]
@Milkhan Thanks for your patience and idea, you can upgrade this package, I add two option, you can modify height and width easily.

**Comment by ek0519** [comment]
> I could find a way to set the height:
> 
> 1- In NovaServiceProvider add a custom css file.
> 
> `
> 
> ```
> public function boot()
> {
> 
>     parent::boot();
> 
>     Nova::style('admin', public_path('css/custom.css')); // Set a custom css file.
> 
> }
> ```
> 
> `
> 
> 1. In the custom.css file (public/css/custom.css)
> 
> `
> height:200px !important;
> 
> ```
> margin-bottom: 50px;
> ```
> 
> `
> 
> I couldn't find a way to make it resizable. This didnt work:
> 
> ` .ql-container {
> 
> ```
> resize: both;
> ```
> 
> overflow: auto;
> 
> }
> `

Thanks for your patience and idea, you can upgrade this package, I add two option, you can modify height and width easily.

**Comment by Milkhan** [comment]
Thank you!
