### ISSUE TITLE
Paragraph Spacing

### ISSUE THREAD

**Issue by mikebertiean** [ek0519/nova-quilljs#5]
Currently in when writing text in 'Normal' text style, and then press Enter, it skips a line.
It looks like it becomes double spaced.

Is it possible when pressing enter to go directly to the line below? (i.e. similar to this text editor on github)
![Screen Shot 2020-03-27 at 11 54 50 AM](https://user-images.githubusercontent.com/3269257/77774644-cd5edf80-7021-11ea-89c7-b1b8d8c8311b.png)

**Comment by mikebertiean** [comment]
I guess my question is, how do we get rid of the margin between paragraphs?
It is saving in the database as:

```
<p>Some test line is here</p>
<p>Then I press enter, and look at the spacing above...</p>
```

Is there a way to add some additional CSS or something to clean up that spacing?

**Comment by ek0519** [comment]
@mikebertiean  Did you ever used medium editor, when you  press Enter, it also creates the next paragraph, it makes sense.

reference [the paragraph's CSS ](https://github.com/ek0519/nova-quilljs/blob/master/resources/js/components/FormField.vue#L167), maybe you can fork this project and override it, but it can't change html's structure, only change paragraph's margin in nova

**Comment by mikebertiean** [comment]
@ek0519 
I see thank you. Yes that would just update the margin in the Nova editor.

If I wanted to add a style inside every paragraph tag to have
`"style:margin=0;"`

Is that possible? Would you be able to point me in the right direction? I can fork and make the necessary updates.

This has already been a really useful tool, thank you so much for developing it and helping me out. 
Much appreciated!

**Comment by ek0519** [comment]
[In this css script ](https://github.com/ek0519/nova-quilljs/blob/master/resources/js/components/FormField.vue#L167)
```
.ql-editor p {
  margin-top: 18px;
  font-size: 18px;
}
```
You can use CSS script  `.ql-editor` to select all content, set p element's style, use the same rule to set other elements' style.

If there are no questions, I will close this issue, God bless Canada :)

**Comment by ek0519** [comment]
@mikebertiean 
[In this css script ](https://github.com/ek0519/nova-quilljs/blob/master/resources/js/components/FormField.vue#L167)
```
.ql-editor p {
  margin-top: 18px;
  font-size: 18px;
}
```
You can use CSS script  `.ql-editor` to select all content, set p element's style, use the same rule to set other elements' style.

If there are no questions, I will close this issue, God bless Canada :)
