### ISSUE TITLE
Past as Plaintext

### ISSUE THREAD

**Issue by Muetze42** [ek0519/nova-quilljs#6]
How can I paste text as plain text?

**Comment by ek0519** [comment]
<img width="60" alt="Screen Shot 2020-03-31 at 7 13 40 AM" src="https://user-images.githubusercontent.com/14010093/77970667-55ddc880-731f-11ea-85de-ab77f68e3638.png">
You can use toolbar this function, set config "clean". 

Quilljs can do that as default  [reference](https://quilljs.com/docs/modules/clipboard/), but in this package would not, you can fork this project  and practice it

**Comment by Muetze42** [comment]
Ok
