### ISSUE TITLE
Editor overlaps fields below it

### ISSUE THREAD

**Issue by sanderbaas** [ek0519/nova-quilljs#8]
The editor overlaps any fields below it (in Firefox) at least.
![image](https://user-images.githubusercontent.com/4152895/86886900-0108d580-c0f8-11ea-9b87-ddaf46d1130a.png)

What solves it for me is setting the height on `.ql-container` instead of `.quill-editor`. Also the `padding-bottom` is not needed that way. Of course the overall height of the editor then exceeds the set height due to the height of the toolbar, but I would prefer that to overlapping.

**Comment by ek0519** [comment]
I release 0.2.1 , resolve editor overlaps problem, thanks.

**Comment by sanderbaas** [comment]
That was quick, thanks a lot. I can confirm the problem is solved!
